language: c++
keep_history: true
allow_empty_commit: true
sudo: required

notifications:
  email:
    recipients:
      - dagmcci@googlegroups.com
  slack: cnerg:d48My26ZXfvHlg0On2WwNQFi

services:
  - docker

before_install:
  # Set some local variables
  - docker_image=svalinn/dagmc-ci-ubuntu-${UBUNTU_VERSION}
  - dagmc_build_dir=/root/build/${COMPILER}/DAGMC-moab-${MOAB_VERSION}-hdf5-${HDF5_VERSION}
  - script_dir=${dagmc_build_dir}/DAGMC/scripts
  - docker_env=${script_dir}/env.sh
  - travis_env=~/travis_env
  # Create a file which contains variables needed by Docker
  - |
    printf "COMPILER=${COMPILER}
    HDF5_VERSION=${HDF5_VERSION}
    MOAB_VERSION=${MOAB_VERSION}
    TRAVIS_REPO_SLUG=${TRAVIS_REPO_SLUG}
    TRAVIS_PULL_REQUEST=${TRAVIS_PULL_REQUEST}
    MW_REG_TEST_MODELS_URL=${MW_REG_TEST_MODELS_URL}
    docker_env=${docker_env}" > ${travis_env}
  # Get the docker image
  - docker pull ${docker_image}
  # Make the build directory
  - docker run --env-file ${travis_env} ${docker_image} /bin/bash -c "mkdir -p ${dagmc_build_dir}"
  - container_id=$(docker ps -lq | tail -n1)
  # Copy the repo in the docker instance
  - docker cp ../DAGMC ${container_id}:${dagmc_build_dir}
  # Commit change in the container
  - docker commit ${container_id} ${docker_image}

install:
  # Build and install DAGMC
  - docker run --env-file ${travis_env} ${docker_image} /bin/bash -c "${script_dir}/travis.install.sh";
  # Commit change in the container
  - container_id=$(docker ps -lq | tail -n1)
  - docker commit ${container_id} ${docker_image}

script:
  # Run tests
  - docker run --env-file ${travis_env} ${docker_image} /bin/bash -c "${script_dir}/travis.tests.sh";

jobs:
  fast_finish: true
  include:
    - env: UBUNTU_VERSION=16.04 COMPILER=gcc   HDF5_VERSION=1.10.4 MOAB_VERSION=5.1.0
    - env: UBUNTU_VERSION=16.04 COMPILER=clang HDF5_VERSION=1.10.4 MOAB_VERSION=5.1.0
    - env: UBUNTU_VERSION=18.04 COMPILER=gcc   HDF5_VERSION=1.10.4 MOAB_VERSION=5.1.0
    - env: UBUNTU_VERSION=18.04 COMPILER=clang HDF5_VERSION=1.10.4 MOAB_VERSION=5.1.0
    - env: UBUNTU_VERSION=16.04 COMPILER=gcc   HDF5_VERSION=1.10.4 MOAB_VERSION=master
      if: type != pull_request
    - env: UBUNTU_VERSION=16.04 COMPILER=clang HDF5_VERSION=1.10.4 MOAB_VERSION=master
      if: type != pull_request
    - env: UBUNTU_VERSION=18.04 COMPILER=gcc   HDF5_VERSION=1.10.4 MOAB_VERSION=master
      if: type != pull_request
    - env: UBUNTU_VERSION=18.04 COMPILER=clang HDF5_VERSION=1.10.4 MOAB_VERSION=master
      if: type != pull_request
    - env: UBUNTU_VERSION=16.04 COMPILER=gcc   HDF5_VERSION=1.10.4 MOAB_VERSION=develop
      if: type != pull_request
    - env: UBUNTU_VERSION=16.04 COMPILER=clang HDF5_VERSION=1.10.4 MOAB_VERSION=develop
      if: type != pull_request
    - env: UBUNTU_VERSION=18.04 COMPILER=gcc   HDF5_VERSION=1.10.4 MOAB_VERSION=develop
      if: type != pull_request
    - env: UBUNTU_VERSION=18.04 COMPILER=clang HDF5_VERSION=1.10.4 MOAB_VERSION=develop
      if: type != pull_request
    - stage: housekeeping
      env: UBUNTU_VERSION=18.04 COMPILER=gcc   HDF5_VERSION=1.10.4 MOAB_VERSION=5.1.0
      install: skip # install is not required for house keeping
      script: docker run --env-file ${travis_env} ${docker_image} /bin/bash -c "${script_dir}/travis.housekeeping.sh";
  allow_failures:
    - env: UBUNTU_VERSION=16.04 COMPILER=gcc   HDF5_VERSION=1.10.4 MOAB_VERSION=master
    - env: UBUNTU_VERSION=16.04 COMPILER=clang HDF5_VERSION=1.10.4 MOAB_VERSION=master
    - env: UBUNTU_VERSION=18.04 COMPILER=gcc   HDF5_VERSION=1.10.4 MOAB_VERSION=master
    - env: UBUNTU_VERSION=18.04 COMPILER=clang HDF5_VERSION=1.10.4 MOAB_VERSION=master
    - env: UBUNTU_VERSION=16.04 COMPILER=gcc   HDF5_VERSION=1.10.4 MOAB_VERSION=develop
    - env: UBUNTU_VERSION=16.04 COMPILER=clang HDF5_VERSION=1.10.4 MOAB_VERSION=develop
    - env: UBUNTU_VERSION=18.04 COMPILER=gcc   HDF5_VERSION=1.10.4 MOAB_VERSION=develop
    - env: UBUNTU_VERSION=18.04 COMPILER=clang HDF5_VERSION=1.10.4 MOAB_VERSION=develop
