version: 2.1
jobs:
  house_keeping:
    docker:
      - image: svalinn/dagmc-ci-ubuntu-18.04-housekeeping:latest
        auth: 
          username: $DOCKERHUB_USER
          password: $DOCKERHUB_PASS
    working_directory: /root/build_dir/DAGMC
    steps:
      - checkout
      - run:
          name: Setup environment
          command: |
            echo "export REPO_SLUG=${CIRCLE_PROJECT_USERNAME}/${CIRCLE_PR_REPONAME}" >> $BASH_ENV
            echo "export PULL_REQUEST=${CIRCLE_PR_NUMBER}" >> $BASH_ENV
      - run:
          name: Housekeeping
          command: CI/circleci/housekeeping.sh

  coverage:
    docker:
      - image: valinn/dagmc-ci-ubuntu-18.04-<gcc-ext-hdf5_1.10.4-moab_5.1.0:latest
        auth: 
          username: $DOCKERHUB_USER
          password: $DOCKERHUB_PASS
    working_directory: /root/build_dir/DAGMC
    steps:
      - checkout
      - run:
          name: install cpp-coveralls
          command: pip install --user cpp-coveralls
      - run:
          name: DAGMC coverage
          command: |  
            mkdir -p /bld
            cd bld
            cmake .. -DMOAB_DIR=${moab_install_dir} \
                     -DBUILD_GEANT4=ON \
                     -DGEANT4_DIR=${geant4_install_dir} \
                     -DBUILD_CI_TESTS=ON \
                     -DBUILD_MW_REG_TESTS=OFF \
                     -DBUILD_STATIC_EXE=OFF \
                     -DDOUBLE_DOWN=OFF
            cmake --build .
            ./tests
            coveralls --root . -E ".*gtest.*" -E ".*CMakeFiles.*"


  build_and_test:
    parameters:
      img:
        type: string
      compiler:
        type: string
      hdf5:
        type: string
      moab:
        type: string
      double_down:
        type: string
        default: "OFF"
    docker:
      - image: svalinn/dagmc-ci-ubuntu-<< parameters.img >>-<< parameters.compiler >>-ext-hdf5_<< parameters.hdf5 >>-moab_<< parameters.moab >>:latest
        auth: 
          username: $DOCKERHUB_USER
          password: $DOCKERHUB_PASS
    working_directory: /root/build_dir/DAGMC
    steps:
      - checkout
      - run:
          name: Setup environment
          command: |
            echo "export COMPILER=<< parameters.compiler >>" >> $BASH_ENV
            echo "export SYSTEM=<< parameters.img >>" >> $BASH_ENV
            echo "export MOAB_VERSION=<< parameters.moab >>" >> $BASH_ENV
            echo "export HDF5_VERSION=<< parameters.hdf5 >>" >> $BASH_ENV
            echo "export REPO_SLUG=${CIRCLE_PROJECT_USERNAME}/${CIRCLE_PR_REPONAME}" >> $BASH_ENV
            echo "export PULL_REQUEST=${CIRCLE_PR_NUMBER}" >> $BASH_ENV
            echo "export DOUBLE_DOWN=<< parameters.double_down >>" >> $BASH_ENV
      - run:
          name: Building DAGMC
          command: CI/circleci/install.sh
      - run:
          name: Testing DAGMC
          command: CI/circleci/tests.sh

workflows:
  version: 2
  pull_request: # Run only for PullRequest
    jobs:
      
      - coverage:
          context: dockerhub
          filters:
            branches:
              ignore: develop
      
      - house_keeping:
          context: dockerhub
          matrix:
            parameters:
              img: ["18.04"]


      - build_and_test:
          context: dockerhub
          matrix:
            parameters:
              img: [ "16.04", "18.04"]
              compiler: ["clang", "gcc"]
              hdf5: ["1.10.4"]
              moab: ["5.1.0"]
          requires:
            - house_keeping
          filters:
            branches:
              ignore: develop

  merge:  # Run only on develop change -> when merging a PullRequest
    jobs:
      - build_and_test:
          context: dockerhub
          matrix:
            parameters:
              img: [ "16.04", "18.04"]
              compiler: ["clang", "gcc"]
              hdf5: ["1.10.4"]
              moab: ["5.1.0", "develop", "master"]
          filters:
            branches:
              only: develop
      - build_and_test:
          context: dockerhub
          name: "Double Down"
          img: "18.04"
          compiler: "gcc"
          hdf5: "1.10.4"
          moab: "master"
          double_down: "ON"
          filters:
            branches:
              only: develop
